services:
    wahlrechner-eins:
        container_name: wahlrechner-eins
        image: ghcr.io/wahlrechner/wahlrechner:latest
        command: bash -c 'chmod +x docker/wait-for-it/wait-for-it.sh && chmod +x docker/startup-production.sh && docker/wait-for-it/wait-for-it.sh wahlrechner-eins-db:3306 -t 120 -- docker/startup-production.sh'
        restart: always
        volumes:
            - ./data/wahlrechner-eins/static:/code/assets/
            - ./data/wahlrechner-eins/media:/code/media/
            - ./data/wahlrechner-eins/logs/wahlrechner:/code/logs/
            - ./data/wahlrechner-eins/migrations/wahlrechner:/code/wahlrechner/migrations
            - ./themes:/code/themes
            - ./data/wahlrechner-eins/stats:/code/wahlrechner/stats
        env_file:
            - ./config/global.env
            - ./config/wahlrechner-eins.env
        depends_on:
            - wahlrechner-eins-db

    wahlrechner-eins-db:
        container_name: wahlrechner-eins-db
        image: mariadb
        restart: always
        env_file:
            - ./config/global.env
            - ./config/wahlrechner-eins.env
        volumes:
            - ./data/wahlrechner-eins/mysql:/var/lib/mysql

    wahlrechner-zwei:
        container_name: wahlrechner-zwei
        image: ghcr.io/wahlrechner/wahlrechner:latest
        command: bash -c 'chmod +x docker/wait-for-it/wait-for-it.sh && chmod +x docker/startup-production.sh && docker/wait-for-it/wait-for-it.sh wahlrechner-zwei-db:3306 -t 120 -- docker/startup-production.sh'
        restart: always
        volumes:
            - ./data/wahlrechner-zwei/static:/code/assets/
            - ./data/wahlrechner-zwei/media:/code/media/
            - ./data/wahlrechner-zwei/logs/wahlrechner:/code/logs/
            - ./data/wahlrechner-zwei/migrations/wahlrechner:/code/wahlrechner/migrations
            - ./themes:/code/themes
            - ./data/wahlrechner-zwei/stats:/code/wahlrechner/stats
        env_file:
            - ./config/global.env
            - ./config/wahlrechner-zwei.env
        depends_on:
            - wahlrechner-zwei-db

    wahlrechner-zwei-db:
        container_name: wahlrechner-zwei-db
        image: mariadb
        restart: always
        env_file:
            - ./config/global.env
            - ./config/wahlrechner-zwei.env
        volumes:
            - ./data/wahlrechner-zwei/mysql:/var/lib/mysql

    # TODO: Als Block einer Einheit (wahlrechner-eins und wahlrechner-eins-db) kopieren und immer "eins" mit einer neuen Zahl bzw. Namen per Suchen & Ersetzen austauschen
    # Rest in diesem Block so lassen
    # weiter unten in web noch anpassen

    web:
        container_name: wahlrechner-web
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./web/nginx.conf:/etc/nginx/nginx.conf
            - ./web/cert:/etc/nginx/ssl
            - /etc/letsencrypt:/etc/letsencrypt
            # TODO: Pro Wahlrechner-Instanz müssen hier zwei Zeilen hinzugefügt werden
            - ./data/wahlrechner-eins/static:/wahlrechner-eins/static
            - ./data/wahlrechner-eins/media:/wahlrechner-eins/media
            - ./data/wahlrechner-zwei/static:/wahlrechner-zwei/static
            - ./data/wahlrechner-zwei/media:/wahlrechner-zwei/media
            ## - ./data/wahlrechner-zwei/static:/wahlrechner-zwei/static
            ## - ./data/wahlrechner-zwei/media:/wahlrechner-zwei/media
        depends_on:
            # TODO: Pro Wahlrechner-Instanz muss hier eine Zeile hinzugefügt werden
            - wahlrechner-eins
            - wahlrechner-zwei
            ## - wahlrechner-zwei
